"""Split the existing visual surfaces into finishes without changing their shape.

Run with Python (no dependencies) after changing the finish boundaries. Original
STLs remain the collision geometry; generated STLs are visual surface patches.
All coordinates below are in the original mesh frames, in metres.
"""

import math
import struct
from collections import Counter
from pathlib import Path

ASSETS = Path(__file__).resolve().parents[1] / "pybravo/model/pybravo_urdf/assets"


def read_triangles(name):
    data = (ASSETS / name).read_bytes()
    for index in range(struct.unpack_from("<I", data, 80)[0]):
        values = struct.unpack_from("<12f", data, 84 + index * 50)
        yield [values[start:start + 3] for start in (3, 6, 9)]


def clip(polygon, height, above):
    result = []
    for start, end in zip(polygon, polygon[1:] + polygon[:1]):
        start_inside = (start[2] >= height) if above else (start[2] <= height)
        end_inside = (end[2] >= height) if above else (end[2] <= height)
        if start_inside:
            result.append(start)
        if start_inside != end_inside:
            fraction = (height - start[2]) / (end[2] - start[2])
            result.append(tuple(start[i] + fraction * (end[i] - start[i]) for i in range(3)))
    return result


def write_triangles(name, triangles):
    records = []
    for a, b, c in triangles:
        u = [b[i] - a[i] for i in range(3)]
        v = [c[i] - a[i] for i in range(3)]
        normal = [u[1] * v[2] - u[2] * v[1], u[2] * v[0] - u[0] * v[2], u[0] * v[1] - u[1] * v[0]]
        length = math.sqrt(sum(n * n for n in normal))
        if length < 1e-15:
            continue
        records.append(struct.pack("<12fH", *(n / length for n in normal), *a, *b, *c, 0))
    header = b"pyBravo visual finish; generated by scripts/build_bravo_skin.py".ljust(80, b"\0")
    (ASSETS / name).write_bytes(header + struct.pack("<I", len(records)) + b"".join(records))


def surface_band(source, output, lower=-math.inf, upper=math.inf):
    triangles = []
    for triangle in read_triangles(source):
        polygon = clip(clip(triangle, lower, True), upper, False)
        triangles.extend((polygon[0], polygon[i], polygon[i + 1]) for i in range(1, len(polygon) - 1))
    write_triangles(output, triangles)


def line(start, end, width, depth=-0.00525):
    """A flat, front-facing strip in the gantry's X/Z plane."""
    dx, dz = end[0] - start[0], end[1] - start[1]
    length = math.hypot(dx, dz)
    nx, nz = -dz * width / (2 * length), dx * width / (2 * length)
    a = (start[0] - nx, depth, start[1] - nz)
    b = (end[0] - nx, depth, end[1] - nz)
    c = (end[0] + nx, depth, end[1] + nz)
    d = (start[0] + nx, depth, start[1] + nz)
    return [(a, b, c), (a, c, d)]


# Small single-line lettering is actual mesh geometry, so URDF consumers do not
# need a texture loader, fonts or a browser overlay to display the markings.
GLYPHS = {
    "A": [[(0, 0), (.5, 1), (1, 0)], [(.25, .45), (.75, .45)]],
    "B": [[(0, 0), (0, 1), (.7, 1), (1, .75), (.7, .5), (0, .5)], [(.7, .5), (1, .25), (.7, 0), (0, 0)]],
    "R": [[(0, 0), (0, 1), (.7, 1), (1, .75), (.7, .5), (0, .5)], [(.5, .5), (1, 0)]],
    "V": [[(0, 1), (.5, 0), (1, 1)]],
    "O": [[(.2, 0), (0, .2), (0, .8), (.2, 1), (.8, 1), (1, .8), (1, .2), (.8, 0), (.2, 0)]],
    "G": [[(1, .8), (.8, 1), (.2, 1), (0, .8), (0, .2), (.2, 0), (1, 0), (1, .5), (.55, .5)]],
    "I": [[(.5, 0), (.5, 1)]],
    "L": [[(0, 1), (0, 0), (1, 0)]],
    "E": [[(1, 1), (0, 1), (0, 0), (1, 0)], [(0, .5), (.8, .5)]],
    "N": [[(0, 0), (0, 1), (1, 0), (1, 1)]],
    "T": [[(0, 1), (1, 1)], [(.5, 1), (.5, 0)]],
    "C": [[(1, .85), (.8, 1), (.2, 1), (0, .8), (0, .2), (.2, 0), (.8, 0), (1, .15)]],
    "H": [[(0, 0), (0, 1)], [(1, 0), (1, 1)], [(0, .5), (1, .5)]],
    "S": [[(1, .85), (.8, 1), (.2, 1), (0, .8), (.2, .55), (.8, .45), (1, .2), (.8, 0), (.2, 0), (0, .15)]],
}


def lettering(text, x, z, height):
    triangles = []
    for index, char in enumerate(text):
        for path in GLYPHS[char]:
            points = [(x + (index * .85 + px * .6) * height, z + pz * height) for px, pz in path]
            for start, end in zip(points, points[1:]):
                triangles.extend(line(start, end, height * .07, depth=-.0054))
    return triangles


def details():
    # Trace the real front cover outline to give it a fine dark parting line.
    edges = Counter()
    for triangle in read_triangles("bravo_gantry_cover.stl"):
        if all(abs(vertex[1] + .005) < 1e-7 for vertex in triangle):
            points = [tuple(round(v[i], 7) for i in (0, 2)) for v in triangle]
            for start, end in zip(points, points[1:] + points[:1]):
                edges[tuple(sorted((start, end)))] += 1
    trim = []
    for (start, end), count in edges.items():
        if count == 1 and start != end:
            trim.extend(line(start, end, .0007))
    write_triangles("bravo_cover_trim.stl", trim)

    ink = lettering("AGILENT", -.092, .409, .0035)
    ink.extend(lettering("TECHNOLOGIES", -.092, .4053, .0018))
    ink.extend(lettering("BRAVO", .027, .297, .0034))
    # Dark screw heads on the faceplate.
    for x, z in [(-.107, .416), (.061, .416), (-.106, .294), (.059, .294)]:
        for index in range(16):
            a, b = index * math.tau / 16, (index + 1) * math.tau / 16
            ink.append(((x, -.0054, z), (x + .0011 * math.cos(a), -.0054, z + .0011 * math.sin(a)),
                        (x + .0011 * math.cos(b), -.0054, z + .0011 * math.sin(b))))
    write_triangles("bravo_cover_markings.stl", ink)

    emblem = []
    for index in range(8):
        angle = index * math.tau / 8
        emblem.extend(line((-.099 + .0014 * math.cos(angle), .4093 + .0014 * math.sin(angle)),
                            (-.099 + .003 * math.cos(angle), .4093 + .003 * math.sin(angle)), .00035))
    write_triangles("bravo_brand_emblem.stl", emblem)

    yellow, black = [], []
    for z in (-.208, -.236):
        points = [(-.010, z), (.011, z), (.0005, z + .018)]
        yellow.append(tuple((x, -.0053, height) for x, height in points))
        for start, end in zip(points, points[1:] + points[:1]):
            black.extend(line(start, end, .001, depth=-.00545))
        black.extend(line((.0005, z + .006), (.0005, z + .012), .0014, depth=-.00545))
        black.extend(line((.0005, z + .0035), (.0005, z + .0045), .0014, depth=-.00545))
    write_triangles("bravo_warning_yellow.stl", yellow)
    write_triangles("bravo_warning_ink.stl", black)


def main():
    # The front cover flares out at this height above the narrow support.
    surface_band("xgantry.stl", "bravo_gantry_cover.stl", lower=0.24202)
    surface_band("xgantry.stl", "bravo_front_support.stl", upper=0.24202)
    # The head's parting line and barrel plate are already present in its mesh.
    surface_band("384_head.stl", "bravo_head_upper.stl", lower=0.002)
    surface_band("384_head.stl", "bravo_head_gasket.stl", lower=-0.002, upper=0.002)
    surface_band("384_head.stl", "bravo_head_lower.stl", lower=-0.185, upper=-0.002)
    surface_band("384_head.stl", "bravo_head_tooling.stl", upper=-0.185)
    # The 384 barrels project below the metal plate at z = -0.209 m.
    # Partition existing triangles so the plate stays metallic and only the
    # barrels receive PEEK plastic. Coplanar plate faces stay with the plate.
    plate, barrels = [], []
    for triangle in read_triangles("bravo_head_tooling.stl"):
        is_barrel = all(v[2] <= -.209 + 1e-7 for v in triangle) and any(v[2] < -.209 - 1e-7 for v in triangle)
        (barrels if is_barrel else plate).append(triangle)
    write_triangles("bravo_head_tooling.stl", plate)
    write_triangles("bravo_head_barrels.stl", barrels)
    surface_band("ygantry.stl", "bravo_carriage_cover.stl", lower=-.131)
    surface_band("ygantry.stl", "bravo_carriage_seam.stl", lower=-.135, upper=-.131)
    surface_band("ygantry.stl", "bravo_carriage_trim.stl", upper=-.135)
    details()


if __name__ == "__main__":
    main()
